language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: Dtb0Bf3AlAxeycfJuli46P8kG4B1at89vtMKbLKKGMwgimAWAKayNjJyuM+CaXtSiqeXOZqypKo9ScAjitQk/UTiE/NkScEZgT9wY+E0Cr+OZKBbIOLfKmFBi6+sjJUdJlVpA8aLqINOoeRH0sc6P5NE+g4StXl0C/M4PLBBfkI=
